---
- hosts: all                                          #run the playbook on all servers mentioned in inventory.ini file
  become: true                                        #run with root user
  roles:
    - httpd
    - bsmeding.docker
